# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the project
RUN npm run build

# Expose port (if HTTP mode is used, default is 3000)
EXPOSE 3000

# Default command in MCP mode
CMD ["node", "dist/bin/mcp.js"]
