# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Install missing dependencies required for TypeScript build
RUN npm install ws @types/ws

# Build the TypeScript code
RUN npm run build

# Expose server port (default 3000)
EXPOSE 3000

# Start the MCP server in MCP mode
CMD [ "npm", "run", "mcp" ]
